name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.16.0

      - name: Install dependencies
        run: npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean Droplet
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          echo "Connecting to $SSH_HOST as $SSH_USERNAME..."
          sshpass -p "${SSH_PASS}" ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} "
            set -e
            echo 'Connected to Droplet.'
            cd /var/www/cop4331-group5.xyz/html || { echo 'Directory not found'; exit 1; }
            echo 'Pulling latest code...'
            git pull origin master || { echo 'git pull failed'; exit 1; }
            echo 'Installing dependencies...'
            npm install --legacy-peer-deps || { echo 'npm install failed'; exit 1; }
            echo 'Building project...'
            npm run build || { echo 'Build failed'; exit 1; }
            echo 'Restarting Nginx...'
            systemctl restart nginx || { echo 'Nginx restart failed'; exit 1; }
            echo 'Deployment completed successfully.'
          "
