name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: MERN-COP4331-Group5

      - name: List directory (for debugging)
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing files recursively:"
          ls -R

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.16.0

      - name: Install dependencies (Backend)
        run: |
          cd MERN-COP4331-Group5/backend
          echo "Now in backend folder:"
          pwd
          ls
          npm install --legacy-peer-deps

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: MERN-COP4331-Group5

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean Droplet
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
          cd /var/todoApp/backend
          git pull origin main
          npm install --legacy-peer-deps
          npm run build || true
          pm2 restart server || systemctl restart nginx || true
          EOF
